site_name: Tiger Jin
nav:
  - Home: index.md
  - 计算机工具:
    - Bash工具: tools/Bash.md
  - AI: 
    - 计算机视觉: cv/demo1.md
  - 计算机网络:
    - 图解HTTP: network/book.md
  - 计算机系统原理: computersArch/README.md
  - 数据结构: dataStructure/README.md
theme:
    name: "material"
    palette:
        primary: "black"
        accent: "white"
    language: "zh"
markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
